- name: hostname and hosts configure
  hosts: #all
  become: true

  tasks:
  - name: Set static hostname
    hostname:
      name: ipa-server.lab.local

  - name: Add FQDN to /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "10.10.10.10 ipa-server.lab.local ipa-server"
      state: present