- name: Обновление локальной копии репозитория
  hosts: all
  tasks:

    - name: Запуск команды git pull
      command: git pull
      args:
        chdir: /home/user/perlit/Perlite/perlite/wiki
      become: true