- name: Базовые настройки FreeIPA
  hosts: ipa-servers
  become: true

  tasks:
  # пользователь должен быть в группе wheel (usermod -aG wheel user)
  # dnf update and upgrade
  - name: Password policy # делаем пароль вечным, откючаем необходимость смены пароля через 90 дней
    community.general.ipa_pwpolicy:
      maxpwdlife: 0
      ipa_user: admin
      ipa_pass: password
      ipa_host: ipa-server.lab.local

  - name: Создаем пользователей в FreeIPA
    community.general.ipa_user:
      name: "{{ item }}"
      givenname: "{{ item.split('.')[0] }}"
      sn: "{{ item.split('.')[1] }}"
      password: "passsword_example"
      state: present
      ipa_user: admin
      ipa_pass: password
      ipa_host: ipa-server.lab.local
    with_items:
      - u.user1
      - u.user2
      - u.user3
      - u.user4


  - name: Add users to admins group
    community.general.ipa_group:
      name: admins
      state: present
      ipa_user: admin
      ipa_pass: password
      ipa_host: ipa-server.lab.local
      user:
        - admin
        - u.user1
        - u.user2
        - u.user3
        - u.user4