---
- name: FreeIPA Installation on CentOS 9
  hosts: ipa-servers
  become: true

  tasks:
    
    - name: Install FreeIPA server packages
      dnf:
        name:
          - freeipa-server
          - freeipa-server-dns
          - freeipa-server-trust-ad
        state: latest

    - name: FreeIPA configure
      command: 
        ipa-server-install 
        --setup-dns 
        --auto-forwarders 
        --forward-policy=only 
        --no-ntp 
        --hostname=ipa-server.lab.local 
        --ip-address=10.10.10.10
        --domain=lab.local
        --realm=LAB.LOCAL
        --ds-password=password
        --admin-password=password
        --unattended
      args: # проверка наличия файла /etc/ipa/default.conf , если есть - не запускаем команду
        creates: /etc/ipa/default.conf

    - name: Open necessary ports in Firewall
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      with_items:
        - 53/tcp
        - 53/udp
        - 80/tcp
        - 443/tcp
        - 88/tcp
        - 88/udp
        - 123/udp
        - 389/tcp
        - 636/tcp
        - 464/tcp
        - 464/udp

    - name: Reload Firewall
      systemd:
        name: firewalld.service
        state: restarted


# Брандмауэр

# Необходимо открыть несколько портов, которые используются службами FreeIPA:

# firewall-cmd --permanent --add-port=53/{tcp,udp} --add-port={80,443}/tcp --add-port={88,464}/{tcp,udp} --add-port=123/udp --add-port={389,636}/tcp

# firewall-cmd --reload
        
