- name: Создание обычных пользователей и груп
  become: true
  hosts: ipa-servers

  tasks:

  - name: Создание пользователей в дефолтной группе ipausers
    community.general.ipa_user:
      name: "{{ item }}"
      givenname: "{{ item.split('.')[0] }}"
      sn: "{{ item.split('.')[1] }}"
      password: "FkWTYdpBda"
      state: present
      ipa_user: admin
      ipa_pass: password
      ipa_host: ipa-server.lab.local
    with_items:

    # бухгалтерия
      - u.user1
      - u.user2
      - u.user3
      - u.user4
      - u.user5

    # Закупки
      - u.user6
      - u.user7
      - u.user8
      - u.user9
      - u.user10
    

  # - name: Add users to admins group
  #   community.general.ipa_group:
  #     name: <ГРУППА>
  #     state: present
  #     ipa_user: admin
  #     ipa_pass: password
  #     ipa_host: ipa-server.lab.local
  #     user:
          # - u.user1
          # - u.user2
          # - u.user3
          # - u.user4
          # - u.user5